// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Models.proto

package micro_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserModel struct {
	UserId               int32                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserPwd              string               `protobuf:"bytes,3,opt,name=user_pwd,json=userPwd,proto3" json:"user_pwd,omitempty"`
	UserDate             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=user_date,json=userDate,proto3" json:"user_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserModel) Reset()         { *m = UserModel{} }
func (m *UserModel) String() string { return proto.CompactTextString(m) }
func (*UserModel) ProtoMessage()    {}
func (*UserModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_Models_7f81857631bc92a4, []int{0}
}
func (m *UserModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserModel.Unmarshal(m, b)
}
func (m *UserModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserModel.Marshal(b, m, deterministic)
}
func (dst *UserModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserModel.Merge(dst, src)
}
func (m *UserModel) XXX_Size() int {
	return xxx_messageInfo_UserModel.Size(m)
}
func (m *UserModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserModel.DiscardUnknown(m)
}

var xxx_messageInfo_UserModel proto.InternalMessageInfo

func (m *UserModel) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserModel) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserModel) GetUserPwd() string {
	if m != nil {
		return m.UserPwd
	}
	return ""
}

func (m *UserModel) GetUserDate() *timestamp.Timestamp {
	if m != nil {
		return m.UserDate
	}
	return nil
}

func init() {
	proto.RegisterType((*UserModel)(nil), "micro.service.UserModel")
}

func init() { proto.RegisterFile("Models.proto", fileDescriptor_Models_7f81857631bc92a4) }

var fileDescriptor_Models_7f81857631bc92a4 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xbf, 0x4a, 0xc6, 0x30,
	0x14, 0xc5, 0x89, 0x7f, 0x3e, 0x6d, 0xd4, 0x25, 0x8b, 0x31, 0x08, 0x16, 0xa7, 0x4e, 0x29, 0xe8,
	0xe0, 0x0b, 0xb8, 0x38, 0x08, 0xf2, 0xa1, 0x73, 0x49, 0x9b, 0x6b, 0x09, 0x34, 0xb9, 0x21, 0x49,
	0xed, 0x8b, 0xf8, 0xc0, 0xd2, 0xa4, 0x75, 0xbb, 0x87, 0xdf, 0xe1, 0xdc, 0x1f, 0xbd, 0x7e, 0x47,
	0x0d, 0x53, 0x94, 0x3e, 0x60, 0x42, 0x76, 0x63, 0xcd, 0x10, 0x50, 0x46, 0x08, 0x3f, 0x66, 0x00,
	0x71, 0x3f, 0x22, 0x8e, 0x13, 0xb4, 0xca, 0x9b, 0x56, 0x39, 0x87, 0x49, 0x25, 0x83, 0x6e, 0x2b,
	0x8b, 0x87, 0x8d, 0xe6, 0xd4, 0xcf, 0xdf, 0x6d, 0x32, 0x16, 0x62, 0x52, 0xd6, 0x97, 0xc2, 0xe3,
	0x2f, 0xa1, 0xd5, 0x57, 0x84, 0x90, 0x5f, 0xb0, 0x5b, 0x7a, 0x31, 0x47, 0x08, 0x9d, 0xd1, 0x9c,
	0xd4, 0xa4, 0x39, 0x3f, 0x1e, 0xd6, 0xf8, 0xa6, 0x99, 0xa0, 0x97, 0xeb, 0xe5, 0x94, 0x05, 0x7e,
	0x52, 0x93, 0xa6, 0x3a, 0xfe, 0x67, 0x76, 0x57, 0x58, 0xe7, 0x17, 0xcd, 0x4f, 0x33, 0xcb, 0x23,
	0x1f, 0x8b, 0x66, 0x2f, 0xb4, 0xca, 0x48, 0xab, 0x04, 0xfc, 0xac, 0x26, 0xcd, 0xd5, 0x93, 0x90,
	0x45, 0x49, 0xee, 0x4a, 0xf2, 0x73, 0x57, 0x2a, 0x9b, 0xaf, 0x2a, 0x41, 0x7f, 0xc8, 0xf4, 0xf9,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x60, 0x55, 0x4a, 0xfb, 0x00, 0x00, 0x00,
}
